version: '3.8'

services:
 postgres:
   image: postgres:15
   container_name: postgres_db
   environment:
     POSTGRES_USER: lamadev
     POSTGRES_PASSWORD: 1234
     POSTGRES_DB: school
   ports:
     - '5432:5432'
   volumes:
     - postgres_data:/var/lib/postgresql/data

 nextjs-app:
   build: .
   container_name: nextjs_app
   ports:
     - '3000:3000'
   environment:
     - DATABASE_URL=postgresql://lamadev:1234@postgres:5432/school
     - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_aW50ZXJuYWwtcGVnYXN1cy01My5jbGVyay5hY2NvdW50cy5kZXYk
     - CLERK_SECRET_KEY=sk_test_WXiP3lDAo9ZwTqxTIALn7REvETPcf7REipRF0XQ7TI
     - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
     - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=dgvizgqs3
     - NEXT_PUBLIC_CLOUDINARY_API_KEY=254766822525643
     - CLOUDINARY_API_SECRET=-GuJab7Pp-P2QmYw9RS6PKIuBw0
   depends_on:
     - postgres

volumes:
 postgres_data:
